# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='Date Published')),
            ],
        ),
        migrations.AddField(
            model_name='custdataschem',
            name='schem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custdataschem',
            name='db_created',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='custdataschem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='database',
            name='data_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.CustDataSchem'),
        ),
    ]
