# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DA', '0003_auto_20170824_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='shown',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='custdataschem',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='database',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
