# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA', '0004_auto_20170829_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
